version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: prajodh_test
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - my_network


  springboot:
    build: .
    container_name: my_spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: prajodh_test
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - my_network


networks:
  my_network:
