name: Docker Image CI/CD to AKS

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_publish_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.ART_2 }}" | docker login ghcr.io -u prajodh --password-stdin

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t spring-boot:latest --file Dockerfile .

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.AZURE }}" | docker login prajuinfo.azurecr.io --username prajuinfo --password-stdin

      - name: Tag and Push to ACR
        run: |
          docker tag spring-boot:latest prajuinfo.azurecr.io/spring-boot:latest
          docker push prajuinfo.azurecr.io/spring-boot:latest
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}



      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Create spring-boot deployment if it doesn't exist
        run: |
          kubectl get deployment gs-spring-boot-docker || kubectl apply -f app.yaml

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/gs-spring-boot-docker spring-boot=prajuinfo.azurecr.io/spring-boot:latest
          kubectl rollout status deployment/gs-spring-boot-docker


